FROM rustlang/rust:nightly

WORKDIR /server

RUN apt-get update && apt-get install -y build-essential libssl-dev pkg-config clang llvm-dev libclang-dev
RUN cargo install cargo-watch

COPY . .

RUN cd server

ENTRYPOINT [ "cargo", "watch" ]